### ISSUE TITLE
Doesn't work with parallels docker-machine

### ISSUE THREAD

**Issue by abashev** [bsideup/forward2docker#4]
Maybe it is specific for latest version of docker-machine, not only parallels but

```
# abashev at AlexMBP.local in ~ [12:42:49]
→ docker-machine --version
docker-machine version 0.8.2, build e18a919

# abashev at AlexMBP.local in ~ [12:43:00]
→ eval $(docker-machine env dev)

# abashev at AlexMBP.local in ~ [12:43:05]
→ forward2docker
2016/11/04 12:43:13 machine does not exist
```

**Comment by bsideup** [comment]
@abashev f2d works only with VirtualBox because port forwarding is specific to it. Also, since Docker for Mac is out, I highly recommend to switch because it comes with built-in port forwarding :)

**Comment by abashev** [comment]
Don't want to restart my machine every time docker hang up 😉

**Comment by bsideup** [comment]
You don't have to :) I'm using it for the last half a year, all good so far :)
